/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 *
 * Regenerate it with `pnpm --filter @{{name}}/api db:types`.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

{{#if useAuth}}
export interface Users {
  created_at: Generated<string>;
  hashed_password: string;
  id: Generated<number | null>;
  metadata: string | null;
  username: string;
}

{{/if}}
export interface DB {
{{#if useAuth}}
  users: Users;
{{/if}}
}
